Import('env', 'install_dir')

#===============================================================================
# default list of subdirectories to build
#===============================================================================

sub_directories = ['library', 'executable']


#===============================================================================
# invoke SConscript on each subdirectory
#===============================================================================

for directory_name in sub_directories:
    env.SConscript('%s/SConscript' % directory_name, {'env' : env, 'install_dir' : install_dir})

